### Improved code Part 1

In [37]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out) # Corrected capitalization
    out = self.linear2(out) # Corrected input to linear2
    out = self.sigmoid(out)

    return out

In [38]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4723],
        [0.4574],
        [0.4806],
        [0.4593],
        [0.4567],
        [0.4663],
        [0.4557],
        [0.4576],
        [0.4502],
        [0.4508]], grad_fn=<SigmoidBackward0>)

In [39]:
# show model weight
model.linear1.weight

Parameter containing:
tensor([[-0.0319,  0.2184, -0.0828, -0.3226,  0.2302],
        [ 0.2705,  0.4262, -0.0234,  0.2081, -0.2416],
        [ 0.2834,  0.1032, -0.2331,  0.1708, -0.3148]], requires_grad=True)

In [40]:
model.linear2.weight

Parameter containing:
tensor([[-0.3873, -0.4031,  0.2506]], requires_grad=True)

In [41]:
# show model bias
model.linear1.bias

Parameter containing:
tensor([-0.2323,  0.1786,  0.0721], requires_grad=True)

In [42]:
model.linear2.bias

Parameter containing:
tensor([0.0229], requires_grad=True)

In [43]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Using nn.sequential module

In [44]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out) # Corrected capitalization
    out = self.linear2(out) # Corrected input to linear2
    out = self.sigmoid(out)

    return out

In [45]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4581],
        [0.4525],
        [0.4432],
        [0.4821],
        [0.4676],
        [0.4847],
        [0.4389],
        [0.4892],
        [0.5173],
        [0.4904]], grad_fn=<SigmoidBackward0>)

In [46]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00