### NN module code (single layer)

In [1]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [2]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4551],
        [0.4363],
        [0.3560],
        [0.3962],
        [0.4478],
        [0.4439],
        [0.4990],
        [0.4655],
        [0.3876],
        [0.3516]], grad_fn=<SigmoidBackward0>)

In [4]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.1562, -0.1921,  0.3399, -0.0434,  0.2592]], requires_grad=True)

In [5]:
# show model bias
model.linear.bias

Parameter containing:
tensor([-0.4374], requires_grad=True)

In [13]:
!pip install torchinfo

In [14]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00